# 这是一片中国区域的CH4监测点

# 中心点(经度, 纬度) && 半径(m)
center = [116.3, 39.9]  # 北京市中心附近
radius = 100000  # 100km

# 选择的年份（注意：Sentinel-5P数据从2018年开始）
years = [2019, 2020, 2021, 2022, 2023, 2024]

# 选择每年统计的起止日期
# 为了减少计算量，每年选择一个月的数据
start_date = "07-01"  # 7月1日
end_date = "07-31"    # 7月31日 