# 全球CH4监测配置

# 全球范围的边界框 [西经, 南纬, 东经, 北纬]
bbox = [-180, -90, 180, 90]

# 选择的年份（注意：Sentinel-5P数据从2018年开始）
years = [2019, 2020, 2021, 2022, 2023, 2024]

# 选择每年统计的起止日期
# 为了减少计算量，每年选择一个月的数据
start_date = "07-01"  # 7月1日
end_date = "07-31"    # 7月31日

# 分区统计的网格大小（度）
grid_size = 10  # 将全球划分为10度×10度的网格

# 采样点数量
sample_points = 10  # 随机选择10个区域进行采样统计

# 采样区域大小（度）
sample_region_size = 20  # 每个采样区域为20度×20度 